package com.thingsrun.device.map.vo;

import java.util.Date;

public class BdGatewayInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_gateway_info.device_id
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_gateway_info.info
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_gateway_info.log
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    private String log;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_gateway_info.version
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_gateway_info.state_info
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    private String stateInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_gateway_info.create_time
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_gateway_info.update_time
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_gateway_info.operator
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    private String operator;

    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_gateway_info.device_id
     *
     * @return the value of bd_gateway_info.device_id
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_gateway_info.device_id
     *
     * @param deviceId the value for bd_gateway_info.device_id
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_gateway_info.info
     *
     * @return the value of bd_gateway_info.info
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_gateway_info.info
     *
     * @param info the value for bd_gateway_info.info
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_gateway_info.log
     *
     * @return the value of bd_gateway_info.log
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_gateway_info.log
     *
     * @param log the value for bd_gateway_info.log
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public void setLog(String log) {
        this.log = log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_gateway_info.version
     *
     * @return the value of bd_gateway_info.version
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_gateway_info.version
     *
     * @param version the value for bd_gateway_info.version
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_gateway_info.state_info
     *
     * @return the value of bd_gateway_info.state_info
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public String getStateInfo() {
        return stateInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_gateway_info.state_info
     *
     * @param stateInfo the value for bd_gateway_info.state_info
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public void setStateInfo(String stateInfo) {
        this.stateInfo = stateInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_gateway_info.create_time
     *
     * @return the value of bd_gateway_info.create_time
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_gateway_info.create_time
     *
     * @param createTime the value for bd_gateway_info.create_time
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_gateway_info.update_time
     *
     * @return the value of bd_gateway_info.update_time
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_gateway_info.update_time
     *
     * @param updateTime the value for bd_gateway_info.update_time
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_gateway_info.operator
     *
     * @return the value of bd_gateway_info.operator
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_gateway_info.operator
     *
     * @param operator the value for bd_gateway_info.operator
     *
     * @mbggenerated Thu Apr 12 11:03:52 GMT+08:00 2018
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}